from collections.abc import Sequence
from typing import Protocol

from mod.ipr_asic.schemas.models import (
    APIObject,
    MinerPoolModel,
    PoolConfig,
    SummaryModel,
    SystemInfoModel,
)


class MinerClient(Protocol):
    async def get_system_info(self) -> SystemInfoModel: ...
    async def summary(self) -> SummaryModel: ...
    async def pools(self) -> Sequence[MinerPoolModel]: ...
    async def get_pool_conf(self) -> PoolConfig: ...

    async def update_pool_conf(
        self, urls: list[str], users: list[str], passwds: list[str]
    ) -> APIObject: ...

    async def update_passwd(self, old_passwd: str, new_passwd: str) -> APIObject: ...

    async def blink(self, enabled: bool) -> APIObject: ...
    async def start(self) -> APIObject: ...
    async def stop(self) -> APIObject: ...
    async def restart(self) -> APIObject: ...
    async def reboot(self) -> APIObject: ...

    def error(self) -> Exception | None: ...
    def set_error(self, ex: Exception) -> None: ...
    def close(self, ex: Exception | None = None) -> None: ...
