name: Test ListenerManager

on:
  push:
    paths:
      - "src/mod/lm/**"

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get system dependencies
        run: sudo apt update && sudo apt install libegl1 -y
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Get python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyside6 pydantic
      - name: Run tests with unittest
        run: |
          cd src/ && python -m unittest discover tests/
